#pragma once

#include "dlist.h"
#include "lvgl.h"
#include "osd_shared.h"
#include "tab_shared.h"

#include <stdbool.h>

typedef enum TabID {
    kTabID_Status,
    kTabID_Display,
    kTabID_Controls,
    kTabID_Palette,
    kTabID_ColorTemp,
    kTabID_System,
    kNumTabIDs,

    kTabID_First = 0,
    kTabID_Last  = kNumTabIDs - 1,
} TabID_t;

typedef struct MenuTab {
    OSD_Widget_t Widget;

    // The accent color of a menu defined as RGB565, specified by the user.
    lv_color_t Accent;

    // A pointer to the image object drawn to the screen. User must not modify this!
    lv_obj_t* pImgObj;

    // A pointer to the image descriptor typically generated by the image converter tool.
    lv_img_dsc_t const *const pImageDesc;

    // A pointer to a the contents of the menu.
    union {
        TabCollection_t* Menu;
    };

    // Optional: if NULL, tab is always active; otherwise evaluated during left/right tab navigation.
    bool (*fnIsActive)(void);

} MenuTab_t;

OSD_Result_t MenuMgr_Initialize(OSD_Widget_t* const pWidget, lv_obj_t *const pScreen);
OSD_Result_t MenuMgr_AddTab(TabID_t eID, MenuTab_t *const pTab);
